name: NonDex Flaky Test Check

on:
  push:
    branches:
      - fix-flaky-FragmentCollectorTest-v3
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests without NonDex
        run: mvn -B test -Dtest=org.mybatis.dynamic.sql.util.FragmentCollectorTest#testWhereFragmentCollectorMerge

      - name: Run tests with NonDex
        run: mvn -pl . edu.illinois:nondex-maven-plugin:2.1.1:nondex -DnondexRuns=20 -Dtest=org.mybatis.dynamic.sql.util.FragmentCollectorTest#testWhereFragmentCollectorMerge
